# Coverage section
[html]
directory = ['tests/coverage_html_report']

[run]
branch = ['True']

[paths]
source = ['src/']

# Autoformatter section
[tool.autopep8]
max_line_length = 180 # This feature doesn't work now. Please change [tool.pylint.'FORMAT'] max-line-length as well when change is required
ignore = "E303,E306"

# Pylint section
[tool.pylint]
    [tool.pylint.master]
    ignore=['CVS']
    jobs=0
    persistent=['yes']
    suggestion-mode=['yes']
    unsafe-load-any-extension=['no']

    [tool.pylint.'MESSAGES CONTROL']
    disable=['print-statement,parameter-unpacking,unpacking-in-except,old-raise-syntax,backtick,long-suffix,old-ne-operator,old-octal-literal,import-star-module-level,non-ascii-bytes-literal,raw-checker-failed,bad-inline-option,locally-disabled,file-ignored,suppressed-message,useless-suppression,deprecated-pragma,use-symbolic-message-instead,apply-builtin,basestring-builtin,buffer-builtin,cmp-builtin,coerce-builtin,execfile-builtin,file-builtin,long-builtin,raw_input-builtin,reduce-builtin,standarderror-builtin,unicode-builtin,xrange-builtin,coerce-method,delslice-method,getslice-method,setslice-method,no-absolute-import,old-division,dict-iter-method,dict-view-method,next-method-called,metaclass-assignment,indexing-exception,raising-string,reload-builtin,oct-method,hex-method,nonzero-method,cmp-method,input-builtin,round-builtin,intern-builtin,unichr-builtin,map-builtin-not-iterating,zip-builtin-not-iterating,range-builtin-not-iterating,filter-builtin-not-iterating,using-cmp-argument,eq-without-hash,div-method,idiv-method,rdiv-method,exception-message-attribute,invalid-str-codec,sys-max-int,bad-python3-import,deprecated-string-function,deprecated-str-translate-call,deprecated-itertools-function,deprecated-types-field,next-method-defined,dict-items-not-iterating,dict-keys-not-iterating,dict-values-not-iterating,deprecated-operator-function,deprecated-urllib-function,xreadlines-attribute,deprecated-sys-function,exception-escape,comprehension-escape,missing-docstring,wrong-import-position,trailing-whitespace']
    enable=['c-extension-no-member']

    [tool.pylint.'REPORTS']
    evaluation=['10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10)']
    output-format=['text']
    reports=['no']
    score=['yes']

    [tool.pylint.'REFACTORING']
    max-nested-blocks=5
    never-returning-functions=['sys.exit']

    [tool.pylint.'MISCELLANEOUS']
    notes=['FIXME,XXX']

    [tool.pylint.'TYPECHECK']
    contextmanager-decorators=['contextlib.contextmanager']
    ignore-mixin-members=['yes']
    ignore-on-opaque-inference=['yes']
    ignored-classes=['optparse.Values,thread._local,_thread._local']
    missing-member-hint=['yes']
    missing-member-hint-distance=1
    missing-member-max-choices=1

    [tool.pylint.'FORMAT']
    ignore-long-lines=['^\s*(# )?<?https?://\S+>?$']
    indent-after-paren=4
    indent-string='    ' # 4 spaces
    max-line-length=180 # do not forget to change the line length at [tool.autopep8] as well
    max-module-lines=1000
    no-space-check=['trailing-comma,dict-separator']
    single-line-class-stmt=['no']
    single-line-if-stmt=['no']

    [tool.pylint.'LOGGING']
    logging-format-style=['old']
    logging-modules=['logging']

    [tool.pylint.'BASIC']
    argument-naming-style=['snake_case']
    attr-naming-style=['snake_case']
    bad-names=['foo,bar,baz,toto,tutu,tata']
    class-naming-style=['PascalCase']
    const-naming-style=['UPPER_CASE']
    docstring-min-length=-1
    function-naming-style=['snake_case']
    good-names=['i,j,k,ex,Run,_,x,y,o,id']
    include-naming-hint=['yes']
    method-naming-style=['snake_case']
    module-naming-style=['snake_case']
    no-docstring-rgx=['^_']
    property-classes=['abc.abstractproperty']
    variable-naming-style=['snake_case']

    [tool.pylint.'VARIABLES']
    allow-global-unused-variables=['yes']
    callbacks=['cb_,_cb']
    dummy-variables-rgx=['_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_']
    ignored-argument-names=['_.*|^ignored_|^unused_']
    init-import=['no']
    redefining-builtins-modules=['six.moves,future.builtins']

    [tool.pylint.'SIMILARITIES']
    ignore-comments=['yes']
    ignore-docstrings=['yes']
    ignore-imports=['no']
    min-similarity-lines=4

    [tool.pylint.'SPELLING']
    max-spelling-suggestions=4
    spelling-store-unknown-words=['no']

    [tool.pylint.'DESIGN']
    max-args=8
    max-attributes=7
    max-bool-expr=5
    max-branches=12
    max-locals=20
    max-parents=7
    max-public-methods=20
    max-returns=6
    max-statements=50
    min-public-methods=2

    [tool.pylint.'IMPORTS']
    allow-wildcard-with-all=['no']
    analyse-fallback-blocks=['no']
    deprecated-modules=['optparse,tkinter.tix']
    known-third-party=['enchant']

    [tool.pylint.'CLASSES']
    defining-attr-methods=['__init__,__new__,setUp']
    exclude-protected=['_asdict,_fields,_replace,_source,_make']
    valid-classmethod-first-arg=['cls']
    valid-metaclass-classmethod-first-arg=['cls']

    [tool.pylint.'EXCEPTIONS']
    overgeneral-exceptions=['Exception']


